### ISSUE TITLE
Merge ARC and CTAC committee

### ISSUE THREAD

**Issue by djp3** [djp3/WestmontFacultyHandbook#12]
Hello Don,

Thanks for collecting the committee information.  I'm writing on behalf of the ARC (of which I am chair) and CTAC committees.

During our discussion today, it became clear that there is much overlap in these two committees.  Further, there is also overlap in that neither of the committees has been active for some time.   In fact, in Nov 2019 Mark Sargent wrote a memo to Senate proposing that the ARC committee be re-imagined.  CTAC did not meet at all last year, and is supposedly chaired by the Director of Informational Technology, a position that no longer exists at Westmont.  This same Director is also a member of the ARC committee.  Both of these committees feel that the membership and directives of the committees are from a different era, and need to have a re-imagining in structure and mission.

The CTAC is supposed to serve as an advisory committee to IT, but has not been serving in that role.  There are very live questions about how much advising IT wants and needs from faculty, and concerns that faculty have not had a "seat at the table" in recent decision-making.

The ARC committee also is concerned with technology, but also is tasked with advising and collaborating with the Library as well as general academic resources for faculty.   The chair of ARC (me) now sits on the CIP committee, which is not codified in the handbook or listed in the tasks of the committee, though clearly is connected to serving faculty resources.

Next steps?  A listening session and brainstorming session with the Provost office, IT, and the Library about how to collaborate and what kind of committee would best serve that goal and serve the interests of the faculty as well.  After those sessions, an update to the ARC and CTAC (Do they become one committee?  Do they go away?) in the handbook.

All people at our table felt it was important for better communication between faculty, IT, and the library, with buy-in from all areas.  Having more robust committee structure and function would serve the needs of all concerned.

Best,
Mitchell

**Comment by Jesserink** [comment]
Dear Jesse,

I hope you are very well!

I am sending this [shared doc](https://docs.google.com/document/d/1Sx3aUMdQIqIPX9AgzyO_HrQHSrlpHb7g_96AeNgsJEs/edit#heading=h.kvb27j9sglsg) containing a draft replacement for the ARC committee description in the faculty handbook.  This document is the culmination of a year-long process of meeting in 2021-2022 as a committee, meeting with members of CTAC, and reflecting on the nature of the purposes and processes of this committee in 2022 and beyond.

A couple of brief points - which I'm happy to elaborate on at an FC meeting or other conversation:

1) The members have been updated to reflect the new organizational structure at college.
2) We are suggesting that the committee move away from the Senate and into the admin. committee list reporting to the Provost and overseen by Faculty Council.
3) We have updated the purposes both to codify what the committee is currently doing (e.g. CIP process) and to make current how the committee can best serve IT and the Library (and faculty and students) in 2022 and beyond.
4) We are recommending the CTAC committee be terminated, and have folded some of the CTAC purposes into this committee's role.

The overall hope is that this will make ARC more visible, vital, and effective.

Note that the overall number of faculty committee assignments may be +1 even though we are proposing cutting the CTAC, because this committee would no longer have 3 senators attached to it.  Our understanding is that Senate is trying to reduce the number of sub-committees due to workload issues, and the work of this committee seems to function well working with IT, Library, and Provost office - representing across divisions and with student participation.  We do note in our proposal the ideal preferable representation of faculty would be from all three divisions due to the financial decisions of the committee, but realize this can be a challenge for FC.

This proposal comes to you with the full support of all committee members of ARC.

Please let me know what else you may need from me at this time.

Best,
Mitchell (Chair) on behalf of ARC

**Comment by Jesserink** [comment]
https://docs.google.com/document/d/1Sx3aUMdQIqIPX9AgzyO_HrQHSrlpHb7g_96AeNgsJEs/edit?usp=sharing

**Comment by Jesserink** [comment]
New language approved by Academic Senate: 

Updated draft: https://docs.google.com/document/d/1Sx3aUMdQIqIPX9AgzyO_HrQHSrlpHb7g_96AeNgsJEs/edit?usp=sharing

**Comment by amaspark** [comment]
This has been approved by the Faculty and the Board of Trustees, and is now ready to be incorporated into the Handbook.
